import fs from 'fs';
import path from 'path';
import { fileURLToPath, pathToFileURL } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const srcDir = path.join(__dirname, 'src');
const primitivesDir = path.join(srcDir, 'primitives');
const distDir = path.join(__dirname, 'dist');
const themesDistDir = path.join(distDir, 'themes');

// Re-imports src modules with a cache-busting query so `--watch` picks up
// edits (ESM's module cache would otherwise serve the first-loaded copy
// forever within this long-lived process).
async function freshImport(file) {
  const url = `${pathToFileURL(path.join(srcDir, file)).href}?update=${Date.now()}`;
  return import(url);
}

async function loadThemeManifest() {
  return (await freshImport('theme-manifest.js')).themeManifest;
}

const tokenFiles = [
  { key: 'color', file: 'color.json' },
  { key: 'spacing', file: 'spacing.json' },
  { key: 'typography', file: 'typography.json' },
  { key: 'radius', file: 'radius.json' }
];

function loadTokens() {
  const tokens = {};

  for (const { key, file } of tokenFiles) {
    const filePath = path.join(primitivesDir, file);
    const content = fs.readFileSync(filePath, 'utf8');
    tokens[key] = JSON.parse(content);
  }

  return tokens;
}

function buildCss(tokens) {
  const lines = [];

  for (const [group, groupTokens] of Object.entries(tokens)) {
    for (const [name, value] of Object.entries(groupTokens)) {
      lines.push(`  --${group}-${name}: ${value};`);
    }
  }

  return `:root {\n${lines.join('\n')}\n}\n`;
}

// theme.css — defines every --usx-* custom property at its default value.
// Compiled component CSS emits bare var(--usx-*) references (no fallbacks),
// so every manifest entry must be defined here. radius-advanced defaults are
// themselves var(--usx-radius-<group>) references, preserving the
// per-component → group fall-through.
function buildThemeCss(themeManifest) {
  const lines = themeManifest
    .map((t) => `  ${t.cssVar}: ${t.defaultValue};`);

  return `/* GENERATED by build.js from theme-manifest.js — do not edit. */\n:root {\n${lines.join('\n')}\n}\n`;
}

// _hooks.scss — loads the variables module with every CSS variable hook
// enabled. Load this before any component styles to opt in to runtime
// theming. Hook Sass names derive from cssVar: --usx-x → $usx-x-var.
function buildHooksScss(themeManifest) {
  const lines = themeManifest.map(
    (t) => `  $${t.cssVar.slice(2)}-var: ${t.cssVar},`
  );

  return `// GENERATED by build.js from theme-manifest.js \u2014 do not edit.\n// Enables every runtime theming hook. Load before component styles:\n//   @use 'pkg:@solexllc/usx-theme/hooks';\n@forward 'pkg:@solexllc/usx-theme/variables' with (\n${lines.join('\n')}\n);\n`;
}

function buildJs(tokens) {
  return `module.exports = ${JSON.stringify(tokens, null, 2)};\n`;
}

const GENERATED_CSS = '/* GENERATED by build.js from presets.js — do not edit. */\n';

// Resolves every prebuilt preset (derived shades included) once, so the CSS
// files and the Sass registry are guaranteed to agree.
function resolvePresets(themeManifest, derive, PRESETS) {
  return Object.entries(PRESETS).map(([name, overrides]) => {
    const resolved = derive.resolveTheme(overrides, {}, themeManifest);
    return {
      name,
      slug: derive.themeSlug(name),
      colorScheme: derive.colorSchemeOf(resolved),
      entries: derive.themeEntries(resolved, { manifest: themeManifest })
    };
  });
}

// themes/<slug>.css — one `[data-theme="<slug>"]` block per prebuilt theme,
// changed tokens only (theme.css's :root supplies the rest). "Default" has
// nothing to change and is skipped. The bundle of all of them lives at
// themes/all.css rather than themes.css: Sass's pkg: importer tries
// `themes.css` when resolving `pkg:.../themes` and would find both it and the
// Sass module, then fail as ambiguous.
function buildThemeFileCss(theme) {
  const lines = [`  color-scheme: ${theme.colorScheme};`, ...theme.entries.map(([cssVar, value]) => `  ${cssVar}: ${value};`)];
  return `${GENERATED_CSS}[data-theme="${theme.slug}"] {\n${lines.join('\n')}\n}\n`;
}

// _themes-registry.scss — data behind src/_themes.scss: every prebuilt theme
// as a Sass map keyed by CSS variable, plus the :root defaults used to fill
// in tokens a theme doesn't set.
function buildThemesRegistryScss(themeManifest, themes, derive) {
  const themeBlocks = themes.map((theme) => {
    const lines = [`    color-scheme: ${theme.colorScheme},`, ...theme.entries.map(([cssVar, value]) => `    ${cssVar}: ${derive.toSassValue(value)},`)];
    return `  ${theme.slug}: (\n${lines.join('\n')}\n  ),`;
  });
  const defaultLines = themeManifest.map((t) => `  ${t.cssVar}: ${derive.toSassValue(t.defaultValue)},`);
  return [
    '// GENERATED by build.js from presets.js + theme-manifest.js — do not edit.',
    '// Consumed by src/_themes.scss (`pkg:@solexllc/usx-theme/themes`).',
    `$themes: (\n${themeBlocks.join('\n')}\n);`,
    `$defaults: (\n${defaultLines.join('\n')}\n);`,
    ''
  ].join('\n');
}

function writeThemes(themeManifest, derive, PRESETS) {
  const themes = resolvePresets(themeManifest, derive, PRESETS);
  const withTokens = themes.filter((t) => t.entries.length > 0);

  fs.rmSync(themesDistDir, { recursive: true, force: true });
  fs.mkdirSync(themesDistDir, { recursive: true });
  const files = withTokens.map((theme) => {
    const css = buildThemeFileCss(theme);
    fs.writeFileSync(path.join(themesDistDir, `${theme.slug}.css`), css, 'utf8');
    return css.replace(GENERATED_CSS, '');
  });
  fs.writeFileSync(path.join(themesDistDir, 'all.css'), GENERATED_CSS + files.join('\n'), 'utf8');
  fs.writeFileSync(path.join(distDir, '_themes-registry.scss'), buildThemesRegistryScss(themeManifest, themes, derive), 'utf8');
  return withTokens.map((t) => t.slug);
}

async function build() {
  const themeManifest = await loadThemeManifest();
  const derive = await freshImport('derive.js');
  const { PRESETS } = await freshImport('presets.js');
  const tokens = loadTokens();

  fs.mkdirSync(distDir, { recursive: true });

  fs.writeFileSync(path.join(distDir, 'tokens.css'), buildCss(tokens), 'utf8');
  fs.writeFileSync(path.join(distDir, 'theme.css'), buildThemeCss(themeManifest), 'utf8');
  fs.writeFileSync(path.join(distDir, '_hooks.scss'), buildHooksScss(themeManifest), 'utf8');
  fs.writeFileSync(path.join(distDir, 'tokens.js'), buildJs(tokens), 'utf8');
  fs.writeFileSync(
    path.join(distDir, 'theme-manifest.json'),
    JSON.stringify(themeManifest, null, 2) + '\n',
    'utf8'
  );
  const slugs = writeThemes(themeManifest, derive, PRESETS);

  console.log(`[${new Date().toLocaleTimeString()}] Built tokens to dist/ (tokens.css, theme.css, _hooks.scss, tokens.js, theme-manifest.json, _themes-registry.scss, themes/{all,${slugs.join(',')}}.css)`);
}

// `node build.js --watch` rebuilds on every change under src/ (primitives
// JSON, theme-manifest.js, etc.) instead of exiting after one build — handy
// alongside `storybook dev` so token edits show up without a manual rebuild.
async function watch() {
  await build().catch((err) => console.error(err));

  let pending = false;
  const rebuild = () => {
    if (pending) return;
    pending = true;
    // Debounce: editors often emit several fs events per save.
    setTimeout(async () => {
      pending = false;
      try {
        await build();
      } catch (err) {
        console.error(err);
      }
    }, 100);
  };

  fs.watch(srcDir, { recursive: true }, (_event, filename) => {
    if (filename) rebuild();
  });

  console.log(`Watching ${srcDir} for changes...`);
}

if (process.argv.includes('--watch')) {
  watch();
} else {
  build().catch((err) => {
    console.error(err);
    process.exitCode = 1;
  });
}
