// contract-check.mjs — CMS contract parity & consistency test.
//
// Asserts the published CMS contract manifest (packages/core/src/contracts.js,
// generated by scripts/generate-contracts.cjs from every component's
// config.json) is internally consistent and stays in sync with the source
// components directory. See solex-cms-overview.md for the contract's consumer.
//
// Usage: node test/contract-check.mjs   (from packages/usx-stories)

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { componentContracts } from '@solexllc/usx-react/contracts';

const pkgDir = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const componentsDir = path.resolve(pkgDir, '..', 'core', 'src', 'components');

const LEGACY_TYPES = new Set(['func', 'json', 'node', 'enum']);
const errors = [];

function checkProp(componentName, propPath, prop, contractsByName) {
  if (LEGACY_TYPES.has(prop.type) || (Array.isArray(prop.type) && prop.type.some((t) => LEGACY_TYPES.has(t)))) {
    errors.push(`${componentName}: ${propPath} uses legacy type "${JSON.stringify(prop.type)}"`);
  }
  if (prop.type === 'select' && (!Array.isArray(prop.options) || prop.options.length === 0)) {
    errors.push(`${componentName}: ${propPath} is type "select" but has no options`);
  }
  if (prop.component) {
    const ref = contractsByName[prop.component];
    if (!ref) {
      errors.push(`${componentName}: ${propPath} references unknown component "${prop.component}"`);
    } else if (prop.omit) {
      const refPropNames = new Set(Object.keys(ref.props || {}));
      prop.omit.forEach((name) => {
        if (!refPropNames.has(name)) {
          errors.push(`${componentName}: ${propPath} omits "${name}", which is not a prop of component "${prop.component}"`);
        }
      });
    }
  } else if (prop.omit) {
    errors.push(`${componentName}: ${propPath} sets "omit" without "component"`);
  }
  if (prop.items) checkProp(componentName, `${propPath}.items`, prop.items, contractsByName);
  if (prop.properties) {
    for (const [key, value] of Object.entries(prop.properties)) {
      checkProp(componentName, `${propPath}.properties.${key}`, value, contractsByName);
    }
  }
}

// Parity: one contract entry per component directory with a config.json.
const componentDirs = fs
  .readdirSync(componentsDir, { withFileTypes: true })
  .filter((e) => e.isDirectory() && fs.existsSync(path.join(componentsDir, e.name, 'config.json')))
  .map((e) => e.name)
  .sort();

const contractsByName = componentContracts.components;
const contractNames = Object.keys(contractsByName).sort();

if (componentContracts.library !== 'usx') {
  errors.push(`manifest library is "${componentContracts.library}", expected "usx"`);
}
if (!Number.isInteger(componentContracts.schemaVersion) || componentContracts.schemaVersion < 1) {
  errors.push(`manifest schemaVersion "${componentContracts.schemaVersion}" is not a positive integer`);
}

if (componentDirs.length !== contractNames.length) {
  errors.push(
    `Component count mismatch: ${componentDirs.length} components on disk vs ${contractNames.length} in contracts.js. ` +
      'Run `node scripts/generate-contracts.cjs` to regenerate.'
  );
} else {
  for (let i = 0; i < componentDirs.length; i++) {
    if (componentDirs[i] !== contractNames[i]) {
      errors.push(`Component parity mismatch at index ${i}: "${componentDirs[i]}" (disk) vs "${contractNames[i]}" (contract)`);
      break;
    }
  }
}

for (const [name, contract] of Object.entries(contractsByName)) {
  if (contract.component !== name) {
    errors.push(`${name}: contract.component is "${contract.component}", expected to match its own dict key "${name}"`);
  }
  if (!Number.isInteger(contract.version) || contract.version < 1) {
    errors.push(`${contract.component}: version "${contract.version}" is not a positive integer`);
  }

  const propNames = new Set(Object.keys(contract.props || {}));
  for (const requiredName of contract.required || []) {
    if (!propNames.has(requiredName)) {
      errors.push(`${contract.component}: required references unknown prop "${requiredName}"`);
    }
  }

  for (const [propName, prop] of Object.entries(contract.props || {})) {
    checkProp(contract.component, propName, prop, contractsByName);
  }
}

if (errors.length) {
  console.error(`FAIL: contract check (${errors.length} issue(s)):`);
  for (const e of errors) console.error(`  - ${e}`);
  process.exit(1);
}

console.log(`PASS: contract check — ${contractNames.length} components, all schema-consistent and in parity with disk.`);
