import React from 'react';

// Each publishable package's CHANGELOG.md is generated by `changeset version`
// (see .changeset/config.json) — this page renders whatever exists at build
// time, so it stays current without manual edits after every release.
const changelogModules = import.meta.glob('../../../*/CHANGELOG.md', {
  eager: true,
  query: '?raw',
  import: 'default',
});

function packageNameFromPath(path, content) {
  const heading = content.match(/^#\s+(.+)$/m);
  if (heading) return heading[1].trim();
  const folder = path.match(/\/([^/]+)\/CHANGELOG\.md$/);
  return folder ? folder[1] : path;
}

// Changesets' generated format: `## <version>` then `### <Major|Minor|Patch>
// Changes` sections, each holding `- ` bullets (sometimes nested, e.g. under
// an "Updated dependencies" bullet).
function parseChangelog(content) {
  const versions = [];
  let current = null;
  for (const line of content.split('\n')) {
    const versionMatch = line.match(/^##\s+(.+)/);
    const sectionMatch = line.match(/^###\s+(.+)/);
    const itemMatch = line.match(/^(\s*)-\s+(.+)/);
    if (versionMatch) {
      current = { version: versionMatch[1].trim(), sections: [] };
      versions.push(current);
    } else if (current && sectionMatch) {
      current.sections.push({ heading: sectionMatch[1].trim(), items: [] });
    } else if (current && itemMatch && current.sections.length) {
      const section = current.sections[current.sections.length - 1];
      section.items.push({ indent: itemMatch[1].length, text: itemMatch[2] });
    }
  }
  return versions;
}

// Renders `[text](url)` and `` `code` `` inside a changelog line; everything
// else in these files is plain text.
function renderInline(text) {
  const parts = [];
  const re = /\[([^\]]+)\]\(([^)]+)\)|`([^`]+)`/g;
  let lastIndex = 0;
  let match;
  let key = 0;
  while ((match = re.exec(text))) {
    if (match.index > lastIndex) parts.push(text.slice(lastIndex, match.index));
    if (match[1]) {
      parts.push(
        <a key={key++} href={match[2]} target="_blank" rel="noopener noreferrer">
          {match[1]}
        </a>
      );
    } else {
      parts.push(<code key={key++}>{match[3]}</code>);
    }
    lastIndex = re.lastIndex;
  }
  if (lastIndex < text.length) parts.push(text.slice(lastIndex));
  return parts;
}

// Rebuilds the nested `- ` bullet structure (e.g. "Updated dependencies"
// sub-lists) from each item's leading-whitespace indent.
function renderItems(items) {
  const root = [];
  const stack = [{ indent: -1, children: root }];
  items.forEach((item, idx) => {
    const node = { text: item.text, indent: item.indent, children: [], key: idx };
    while (stack.length > 1 && item.indent <= stack[stack.length - 1].indent) stack.pop();
    stack[stack.length - 1].children.push(node);
    stack.push({ indent: item.indent, children: node.children });
  });
  return renderList(root);
}

function renderList(nodes) {
  if (!nodes.length) return null;
  return (
    <ul>
      {nodes.map((n) => (
        <li key={n.key}>
          {renderInline(n.text)}
          {renderList(n.children)}
        </li>
      ))}
    </ul>
  );
}

function PackageChangelog({ name, versions }) {
  return (
    <section>
      <h2>{name}</h2>
      {versions.length === 0 ? (
        <p><em>No releases yet.</em></p>
      ) : (
        versions.map((v) => (
          <div key={v.version}>
            <h3>{v.version}</h3>
            {v.sections.map((s, si) => (
              <div key={si}>
                <h4>{s.heading}</h4>
                {renderItems(s.items)}
              </div>
            ))}
          </div>
        ))
      )}
    </section>
  );
}

const packages = Object.entries(changelogModules)
  .map(([path, content]) => ({
    name: packageNameFromPath(path, content),
    versions: parseChangelog(content),
  }))
  .sort((a, b) => a.name.localeCompare(b.name));

export default {
  title: 'Documentation/Release Notes',
  tags: ['autodocs'],
};

export const ReleaseNotes = {
  render: () => (
    <div className="usa-prose usx-prose" style={{ maxWidth: '840px' }}>
      <h1>Release Notes</h1>
      <p>
        USX's packages are versioned and released independently using{' '}
        <a href="https://github.com/changesets/changesets" target="_blank" rel="noopener noreferrer">
          Changesets
        </a>
        . Each package below keeps its own version number and changelog, so a
        release of one (e.g. <code>@solexllc/usx-theme</code>) doesn't bump the
        others unless they actually depend on what changed.
      </p>

      {packages.length === 0 ? (
        <p><em>No packages have been released yet. Changelogs will appear here after the first release.</em></p>
      ) : (
        packages.map((pkg) => <PackageChangelog key={pkg.name} {...pkg} />)
      )}
    </div>
  ),
};
