// Shared helpers for the repo-level component scripts (generate-exports,
// generate-contracts, validate-configs, new-component). Single source of
// truth for repo paths, config.json loading/validation, and the CMS contract
// manifest shape — so those concerns aren't re-implemented per script.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import Ajv from 'ajv';

export const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
export const CORE_DIR = path.join(REPO_ROOT, 'packages', 'usx-react');
export const COMPONENTS_DIR = path.join(CORE_DIR, 'src', 'components');
export const SCHEMA_PATH = path.join(CORE_DIR, 'config.schema.json');
export const CONTRACTS_PATH = path.join(CORE_DIR, 'src', 'contracts.js');
export const INDEX_PATH = path.join(CORE_DIR, 'src', 'index.js');
export const USX_SCSS_DIR = path.join(REPO_ROOT, 'packages', 'usx', 'src', 'components');
export const STORIES_DIR = path.join(REPO_ROOT, 'packages', 'usx-stories', 'src', 'components');

// Format version of the contract manifest itself (its wrapper shape), distinct
// from each component's own config.json "version".
export const CONTRACT_SCHEMA_VERSION = 1;

export function toPascal(name) {
  return name
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}

export function toKebab(name) {
  return name
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[\s_]+/g, '-')
    .toLowerCase();
}

export function rel(p) {
  return path.relative(REPO_ROOT, p);
}

export function listComponentDirs() {
  return fs
    .readdirSync(COMPONENTS_DIR, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort();
}

// The React entry file for a component dir: `<Pascal>.tsx|jsx`, falling back
// to a case-insensitive match (e.g. `sidenav/` → `SideNav.tsx`). Returns
// { file, exportName } or null when the dir has no component file.
export function findComponentFile(dir) {
  const dirPath = path.join(COMPONENTS_DIR, dir);
  const pascal = toPascal(dir);
  const candidates = fs.readdirSync(dirPath).filter((f) => /\.(tsx|jsx)$/.test(f) && !/\.stories\./.test(f));
  const exact = candidates.find((f) => f.replace(/\.(tsx|jsx)$/, '') === pascal);
  const loose = exact || candidates.find((f) => f.replace(/\.(tsx|jsx)$/, '').toLowerCase() === pascal.toLowerCase());
  if (!loose) return null;
  return { file: loose, exportName: loose.replace(/\.(tsx|jsx)$/, '') };
}

// Source text of packages/usx-react/src/index.js: one export per component dir
// that has a React entry file.
export function buildIndexSource() {
  const lines = [];
  for (const dir of listComponentDirs()) {
    const entry = findComponentFile(dir);
    if (entry) lines.push(`export { default as ${entry.exportName} } from './components/${dir}/${entry.file}';`);
  }
  return `// Auto-generated by scripts/generate-exports.js — do not edit by hand.\n// Run: pnpm generate:exports\n${lines.join('\n')}\n`;
}

function checkComponentRefs(node, propPath, configsByName, errors) {
  if (!node || typeof node !== 'object') return;
  if (node.component) {
    const ref = configsByName.get(node.component);
    if (!ref) {
      errors.push(`${propPath} references unknown component "${node.component}"`);
    } else if (node.omit) {
      const refProps = new Set(Object.keys(ref.props || {}));
      for (const name of node.omit) {
        if (!refProps.has(name)) {
          errors.push(`${propPath} omits "${name}", which is not a prop of component "${node.component}"`);
        }
      }
    }
  } else if (node.omit) {
    errors.push(`${propPath} sets "omit" without "component"`);
  }
  if (node.items) checkComponentRefs(node.items, `${propPath}.items`, configsByName, errors);
  for (const [key, value] of Object.entries(node.properties || {})) {
    checkComponentRefs(value, `${propPath}.properties.${key}`, configsByName, errors);
  }
}

// Loads and validates every component's config.json. Returns
// { configs: Map<name, config>, errors: Map<relPath, string[]> }.
// Validation: JSON Schema (AJV), `required` names real props, and every
// `component`/`omit` cross-reference resolves.
export function loadComponentConfigs() {
  const schema = JSON.parse(fs.readFileSync(SCHEMA_PATH, 'utf8'));
  const validate = new Ajv({ allErrors: true, allowUnionTypes: true }).compile(schema);

  const configs = new Map();
  const errors = new Map();
  const parsed = [];
  const addError = (file, msg) => {
    if (!errors.has(file)) errors.set(file, []);
    errors.get(file).push(msg);
  };

  for (const dir of listComponentDirs()) {
    const file = path.join(COMPONENTS_DIR, dir, 'config.json');
    if (!fs.existsSync(file)) continue;
    const label = rel(file);
    let config;
    try {
      config = JSON.parse(fs.readFileSync(file, 'utf8'));
    } catch (err) {
      addError(label, `failed to parse: ${err.message}`);
      continue;
    }
    if (!validate(config)) {
      for (const e of validate.errors) addError(label, `${e.instancePath || '/'} ${e.message}`);
    }
    if (config.name !== dir) {
      addError(label, `"name" is "${config.name}" but the folder is "${dir}"`);
    }
    const propNames = new Set(Object.keys(config.props || {}));
    for (const name of config.required || []) {
      if (!propNames.has(name)) addError(label, `required references unknown prop "${name}"`);
    }
    configs.set(config.name, config);
    parsed.push({ label, config });
  }

  for (const { label, config } of parsed) {
    const refErrors = [];
    for (const [propName, prop] of Object.entries(config.props || {})) {
      checkComponentRefs(prop, propName, configs, refErrors);
    }
    for (const e of refErrors) addError(label, e);
  }

  return { configs, errors };
}

// The publishable CMS contract manifest (see solex-cms-overview.md). Keyed by
// component name for O(1) lookup. Cross-component `component` refs are kept
// as authored — never inlined — so consumers resolve one hop at a time and
// circular references can't blow up the manifest.
export function buildContractManifest(configs) {
  const components = {};
  for (const name of [...configs.keys()].sort()) {
    const config = configs.get(name);
    components[name] = {
      component: name,
      version: config.version,
      required: config.required || [],
      props: config.props || {},
    };
  }
  return { library: 'usx', schemaVersion: CONTRACT_SCHEMA_VERSION, components };
}

export function printErrors(errors) {
  for (const [file, msgs] of errors) {
    console.error(`\n${file}:`);
    for (const m of msgs) console.error(`  - ${m}`);
  }
}
