import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { themeManifest } from './src/theme-manifest.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const srcDir = path.join(__dirname, 'src');
const primitivesDir = path.join(srcDir, 'primitives');
const distDir = path.join(__dirname, 'dist');

const tokenFiles = [
  { key: 'color', file: 'color.json' },
  { key: 'spacing', file: 'spacing.json' },
  { key: 'typography', file: 'typography.json' },
  { key: 'radius', file: 'radius.json' }
];

function loadTokens() {
  const tokens = {};

  for (const { key, file } of tokenFiles) {
    const filePath = path.join(primitivesDir, file);
    const content = fs.readFileSync(filePath, 'utf8');
    tokens[key] = JSON.parse(content);
  }

  return tokens;
}

function buildCss(tokens) {
  const lines = [];

  for (const [group, groupTokens] of Object.entries(tokens)) {
    for (const [name, value] of Object.entries(groupTokens)) {
      lines.push(`  --${group}-${name}: ${value};`);
    }
  }

  return `:root {\n${lines.join('\n')}\n}\n`;
}

// theme.css — defines every --usx-* custom property at its default value.
// Compiled component CSS emits bare var(--usx-*) references (no fallbacks),
// so every manifest entry must be defined here. radius-advanced defaults are
// themselves var(--usx-radius-<group>) references, preserving the
// per-component → group fall-through.
function buildThemeCss() {
  const lines = themeManifest
    .map((t) => `  ${t.cssVar}: ${t.defaultValue};`);

  return `/* GENERATED by build.js from theme-manifest.js — do not edit. */\n:root {\n${lines.join('\n')}\n}\n`;
}

// _hooks.scss — loads the variables module with every CSS variable hook
// enabled. Load this before any component styles to opt in to runtime
// theming. Hook Sass names derive from cssVar: --usx-x → $usx-x-var.
function buildHooksScss() {
  const lines = themeManifest.map(
    (t) => `  $${t.cssVar.slice(2)}-var: ${t.cssVar},`
  );

  return `// GENERATED by build.js from theme-manifest.js \u2014 do not edit.\n// Enables every runtime theming hook. Load before component styles:\n//   @use 'pkg:@solexllc/usx-theme/hooks';\n@forward 'pkg:@solexllc/usx-theme/variables' with (\n${lines.join('\n')}\n);\n`;
}

function buildJs(tokens) {
  return `module.exports = ${JSON.stringify(tokens, null, 2)};\n`;
}

function run() {
  const tokens = loadTokens();

  fs.mkdirSync(distDir, { recursive: true });

  fs.writeFileSync(path.join(distDir, 'tokens.css'), buildCss(tokens), 'utf8');
  fs.writeFileSync(path.join(distDir, 'theme.css'), buildThemeCss(), 'utf8');
  fs.writeFileSync(path.join(distDir, '_hooks.scss'), buildHooksScss(), 'utf8');
  fs.writeFileSync(path.join(distDir, 'tokens.js'), buildJs(tokens), 'utf8');
  fs.writeFileSync(
    path.join(distDir, 'theme-manifest.json'),
    JSON.stringify(themeManifest, null, 2) + '\n',
    'utf8'
  );

  console.log('Built tokens to dist/ (tokens.css, theme.css, _hooks.scss, tokens.js, theme-manifest.json)');
}

run();
