import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const iconsDir = path.join(__dirname, '..', 'src', 'icons');
const outputPath = path.join(__dirname, '..', 'src', 'img', 'usx-sprite.svg');

function buildSprite() {
  const files = fs.readdirSync(iconsDir).filter((f) => f.endsWith('.svg')).sort();

  const symbols = files.map((file) => {
    const name = path.basename(file, '.svg');
    const raw = fs.readFileSync(path.join(iconsDir, file), 'utf8');

    const openTagMatch = raw.match(/<svg\b[^>]*>/);
    if (!openTagMatch) {
      throw new Error(`${file}: could not find an <svg> root element`);
    }
    const openTag = openTagMatch[0];
    const viewBoxMatch = openTag.match(/viewBox="([^"]+)"/);
    if (!viewBoxMatch) {
      throw new Error(`${file}: <svg> root element is missing a viewBox attribute`);
    }
    const viewBox = viewBoxMatch[1];
    const closeTagIndex = raw.lastIndexOf('</svg>');
    const inner = raw.slice(openTagMatch.index + openTag.length, closeTagIndex).trim();

    return `  <symbol id="${name}" viewBox="${viewBox}">\n    ${inner.replace(/\n\s*/g, '\n    ')}\n  </symbol>`;
  });

  const output = `<svg xmlns="http://www.w3.org/2000/svg">
  <!--
    GENERATED by scripts/build-sprite.mjs from src/icons/*.svg — do not edit.
    Add a new icon by creating src/icons/<name>.svg (a standalone <svg> with
    a viewBox), then run \`pnpm -F @solexllc/usx build\`. Also add a matching
    { name, meta } entry to usx-icons.json for the Documentation/Icons page's
    search.
    Reference icons with: <use href="./img/usx-sprite.svg#icon-name" />
  -->
${symbols.join('\n')}
</svg>
`;

  // XML forbids "--" inside comments; a stray occurrence breaks strict XML
  // parsing of the whole file, which silently kills cross-document <use>.
  for (const comment of output.matchAll(/<!--([\s\S]*?)-->/g)) {
    if (comment[1].includes('--')) {
      throw new Error(`Generated sprite has an invalid XML comment (contains "--"): ${comment[1].trim()}`);
    }
  }

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, output);
  console.log(`Built ${path.relative(process.cwd(), outputPath)} from ${files.length} icon(s).`);
}
buildSprite();

if (process.argv.includes('--watch')) {
  fs.watch(iconsDir, { persistent: true }, () => {
    try {
      buildSprite();
    } catch (err) {
      console.error(err.message);
    }
  });
  console.log(`Watching ${path.relative(process.cwd(), iconsDir)} for changes...`);
}
