#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

function toPascal(name) {
  return name
    .split(/[-_\s]+/)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}

const repoRoot = path.resolve(__dirname, '..');
const componentsDir = path.join(repoRoot, 'packages', 'core', 'src', 'components');
const indexPath = path.join(repoRoot, 'packages', 'core', 'src', 'index.js');

if (!fs.existsSync(componentsDir)) {
  console.error('Components directory not found:', componentsDir);
  process.exit(1);
}

const entries = fs.readdirSync(componentsDir, { withFileTypes: true });
const dirs = entries.filter((e) => e.isDirectory()).map((d) => d.name);

const exportLines = dirs
  .map((dir) => {
    const name = toPascal(dir);
    return `export { default as ${name} } from './components/${dir}';`;
  })
  .sort();

const START = '// AUTO-GENERATED-EXPORTS START';
const END = '// AUTO-GENERATED-EXPORTS END';

const header = `// This file is auto-generated by scripts/generate-exports.cjs
// Exports between the markers will be replaced. Keep manual exports or comments
// outside the markers and they will be preserved.
// To regenerate, run: node scripts/generate-exports.cjs
\n`;

const generatedBlock = [START, ...exportLines, END].join('\n') + '\n';

let finalContent = '';
if (fs.existsSync(indexPath)) {
  const existing = fs.readFileSync(indexPath, 'utf8');
  const startIdx = existing.indexOf(START);
  const endIdx = existing.indexOf(END);
  if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
    // preserve content before START and after END
    const before = existing.slice(0, startIdx);
    const after = existing.slice(endIdx + END.length);
    finalContent = before + generatedBlock + after;
  } else {
    // No markers found: prepend header + generated block and then keep existing file
    finalContent = header + generatedBlock + '\n' + existing;
  }
} else {
  finalContent = header + generatedBlock;
}

fs.writeFileSync(indexPath, finalContent, 'utf8');
console.log('Updated', indexPath);
