#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

/*
HEY, ALEX!

This script sucks. For whatever reason, CoPilot couldn't hack it despite it being relatively straightforward.
Sorry about the headache if you ever have to modify it.

Love,

Alex
*/

function toPascal(name) {
  return name
    .split(/[-_\s]+/)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}

const repoRoot = path.resolve(__dirname, '..');
const componentsDir = path.join(repoRoot, 'packages', 'core', 'src', 'components');
const indexPath = path.join(repoRoot, 'packages', 'core', 'src', 'index.js');

if (!fs.existsSync(componentsDir)) {
  console.error('Components directory not found:', componentsDir);
  process.exit(1);
}

const entries = fs.readdirSync(componentsDir, { withFileTypes: true });
const dirs = entries.filter((e) => e.isDirectory()).map((d) => d.name).sort();

const START_MANUAL = '// MANUAL-EXPORTS START';
const END_MANUAL = '// MANUAL-EXPORTS END';
const START_AUTO = '// AUTO-GENERATED-EXPORTS START';
const END_AUTO = '// AUTO-GENERATED-EXPORTS END';

const header = `/*
This file is auto-generated by scripts/generate-exports.cjs
The generator will always replace the AUTO block below. Put manual exports
or EXCLUDE directives inside the MANUAL block to preserve or alter behavior.
To regenerate, run: node scripts/generate-exports.cjs
*/\n`;

// Read existing manual blocks if present; support multiple blocks and
// consolidate their contents so accidental duplicates are tolerated.
let existing = '';
if (fs.existsSync(indexPath)) {
  existing = fs.readFileSync(indexPath, 'utf8');
}

// Find and preserve the first MANUAL block exactly (immutable).
// Use indexOf-based search to avoid regex edge-cases when reading user-edited files.
let manualBlock = `${START_MANUAL}\n
/*
Use lines like: // EXCLUDE: ComponentName
to prevent automatic generation for a component.
# Example
- Uncomment the following two lines to include an export for
  MyComponent and to exclude a Button export:
export { default as MyComponent } from './components/MyComponent';
EXCLUDE: Button
*/
// ${END_MANUAL}
// \n\n`;
let manualConfigText = '';
const manualStartIdx = existing.indexOf(START_MANUAL);
if (manualStartIdx !== -1) {
  const manualEndIdx = existing.indexOf(END_MANUAL, manualStartIdx);
  if (manualEndIdx !== -1) {
    const manualEndPos = manualEndIdx + END_MANUAL.length;
    manualBlock = existing.slice(manualStartIdx, manualEndPos);
    // inner text between the markers
    manualConfigText = existing.slice(manualStartIdx + START_MANUAL.length, manualEndIdx);
  }
}

// Strip JS-style comments from the manual config before parsing so that
// commented-out EXCLUDE lines are ignored by the generator.
const manualConfigNoComments = manualConfigText
  .replace(/\/\*[\s\S]*?\*\//g, '') // remove /* block comments */
  .replace(/\/\/.*$/gm, ''); // remove // line comments

// EXCLUDE extraction: only from uncommented text
const excludeRe = /EXCLUDE:\s*([A-Za-z0-9_\-]+)/gi;
const excludes = new Set();
let excl;
while ((excl = excludeRe.exec(manualConfigNoComments)) !== null) {
  excludes.add(excl[1].trim());
}

// Find any explicit manual export names (uncommented) to avoid duplicating them.
const manualExportRe = /export\s+\{\s*default\s+as\s+([A-Za-z0-9_]+)\s*\}\s+from\s+['"]\.\/components\/[\w-]+['"];?/gi;
const manualNames = new Set();
let mex;
while ((mex = manualExportRe.exec(manualConfigNoComments)) !== null) {
  manualNames.add(mex[1]);
}

// Build auto export lines, skipping excludes
const exportLines = dirs
  .filter((dir) => {
    const name = toPascal(dir);
    return !excludes.has(name) && !manualNames.has(name);
  })
  .map((dir) => {
    const name = toPascal(dir);
    return `export { default as ${name} } from './components/${dir}';`;
  });

const autoBlock = `${START_AUTO}\n${exportLines.join('\n')}\n${END_AUTO}\n`;

// If an existing file contains START_AUTO/END_AUTO, replace that block
// with the newly generated autoBlock. If not, and a manual block exists,
// insert the autoBlock immediately after the manual block. If neither
// exist, write a fresh header+manual+auto layout.
let out = '';
if (existing) {
  const startAutoIdx = existing.indexOf(START_AUTO);
  const endAutoIdx = existing.indexOf(END_AUTO);
  if (startAutoIdx !== -1 && endAutoIdx !== -1 && endAutoIdx > startAutoIdx) {
    // replace existing auto block
    out = existing.slice(0, startAutoIdx) + autoBlock + existing.slice(endAutoIdx + END_AUTO.length);
  } else if (manualMatch) {
    // insert autoBlock after the preserved manual block
    const manualIdx = existing.indexOf(manualMatch[0]);
    const afterManual = manualIdx + manualMatch[0].length;
    out = existing.slice(0, afterManual) + '\n' + autoBlock + existing.slice(afterManual);
  } else {
    // no manual or auto blocks: write header, manualBlock, autoBlock
    out = header + manualBlock + autoBlock;
  }
} else {
  out = header + manualBlock + autoBlock;
}

fs.writeFileSync(indexPath, out, 'utf8');
console.log('Updated', indexPath);

// ─── Per-component barrel index.js files ─────────────────────────────────────
// Each component folder gets a tiny index.js that re-exports the default React
// component. This lets the root src/index.js resolve `from './components/button'`
// (a directory) correctly for both Node and Vite consumers.

for (const dir of dirs) {
  const name = toPascal(dir);
  const componentFile = path.join(componentsDir, dir, `${name}.jsx`);
  const barrelPath = path.join(componentsDir, dir, 'index.js');

  // Only create/overwrite the barrel if the component file actually exists.
  if (!fs.existsSync(componentFile)) continue;

  const barrelContent = `// Auto-generated — do not edit by hand. Run: node scripts/generate-exports.cjs\nexport { default } from './${name}.jsx';\n`;
  fs.writeFileSync(barrelPath, barrelContent, 'utf8');
}

console.log('Updated per-component index.js barrels');

// ─── core.scss regeneration ──────────────────────────────────────────────────

const scssPath = path.join(repoRoot, 'packages', 'core', 'src', 'styles', 'core.scss');

const SCSS_START_AUTO = '// AUTO-GENERATED-SCSS START';
const SCSS_END_AUTO   = '// AUTO-GENERATED-SCSS END';
const SCSS_START_MANUAL = '// MANUAL-SCSS START';
const SCSS_END_MANUAL   = '// MANUAL-SCSS END';

// Build @use lines for every component dir that has a matching <name>.scss file.
const scssUseLines = dirs
  .filter((dir) => {
    const scssFile = path.join(componentsDir, dir, `${dir}.scss`);
    return fs.existsSync(scssFile);
  })
  .map((dir) => `@use '../components/${dir}/${dir}';`);

const scssAutoBlock = `${SCSS_START_AUTO}\n${scssUseLines.join('\n')}\n${SCSS_END_AUTO}`;

let existingScss = '';
if (fs.existsSync(scssPath)) {
  existingScss = fs.readFileSync(scssPath, 'utf8');
}

let scssOut = '';
const scssAutoStartIdx = existingScss.indexOf(SCSS_START_AUTO);
const scssAutoEndIdx   = existingScss.indexOf(SCSS_END_AUTO);

if (scssAutoStartIdx !== -1 && scssAutoEndIdx !== -1 && scssAutoEndIdx > scssAutoStartIdx) {
  // Replace just the auto block; leave the manual block untouched.
  scssOut = existingScss.slice(0, scssAutoStartIdx)
    + scssAutoBlock
    + existingScss.slice(scssAutoEndIdx + SCSS_END_AUTO.length);
} else {
  // First run: migrate existing core.scss.
  // Preserve any non-component-@use content as the manual block.
  // Identify lines that are auto-generated component @use statements.
  const componentDirSet = new Set(dirs);
  const manualLines = [];
  for (const line of existingScss.split('\n')) {
    const match = line.match(/^@use\s+['"]\.\.\/components\/([\w-]+)\//);
    if (match && componentDirSet.has(match[1])) continue; // will be auto-generated
    manualLines.push(line);
  }
  // Trim leading/trailing blank lines from the manual section.
  const manualContent = manualLines.join('\n').trim();
  const scssManualBlock = `${SCSS_START_MANUAL}\n${manualContent}\n${SCSS_END_MANUAL}`;
  scssOut = `${scssAutoBlock}\n\n${scssManualBlock}\n`;
}

fs.writeFileSync(scssPath, scssOut, 'utf8');
console.log('Updated', scssPath);
